import { Exercise, ACLSafetyTier } from "./types";

// --- THE "MAIN ROSTER" & "BENCH" DATA STRUCTURE ---
export const MASTER_EXERCISE_DATABASE: Exercise[] = [
  // =========================================
  // LEGS A (Focus: Quads/Glutes Safe Loading)
  // =========================================
  {
    id: "leg_press_linear_01",
    name: "Linear Leg Press",
    target_muscle: "Quadriceps, Glutes",
    machine_type: "Plate Loaded Linear Press",
    default_reps: 12,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: ["hack_squat_01"],
    tags: ["quad_compound", "legs_push"],
    day_assignment: "Legs_A",
    circuit_id: "1",
    description: "Primary Closed Kinetic Chain. Keep feet high for glute bias.",
  },
  {
    id: "hamstring_curl_seated_01",
    name: "Seated Hamstring Curl",
    target_muscle: "Hamstrings",
    machine_type: "Selectorized",
    default_reps: 15,
    default_sets: 4,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: ["hamstring_curl_lying_01"],
    tags: ["hamstring_isolation"],
    day_assignment: "Legs_A",
    circuit_id: "1",
    description: "Essential for graft protection.",
  },
  {
    id: "calf_raise_seated_01",
    name: "Seated Calf Raise",
    target_muscle: "Soleus",
    machine_type: "Plate Loaded",
    default_reps: 15,
    default_sets: 4,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: [],
    tags: ["calf_isolation"],
    day_assignment: "Legs_A",
    circuit_id: "1",
    description: "Focus on full stretch at the bottom.",
  },
  {
    id: "leg_extension_01",
    name: "Leg Extension (Limited ROM)",
    target_muscle: "Quadriceps",
    machine_type: "Selectorized",
    default_reps: 15,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_3_AVOID,
    status: "Active", 
    compatible_swaps: ["cable_terminal_knee_extension"],
    tags: ["quad_isolation"],
    day_assignment: "Legs_A",
    circuit_id: "2",
    description: "High Risk. Only perform 90-45 degrees (avoid full extension) if ACL is healing.",
  },
  {
    id: "hip_abduction_machine_01",
    name: "Hip Abduction Machine",
    target_muscle: "Glute Medius",
    machine_type: "Selectorized",
    default_reps: 20,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: ["cable_hip_abduction"],
    tags: ["abduction_isolation"],
    day_assignment: "Legs_A",
    circuit_id: "2",
    description: "Builds lateral stability to prevent knee caving (valgus).",
  },
  {
    id: "glute_drive_machine_01",
    name: "Glute Drive Machine",
    target_muscle: "Glutes",
    machine_type: "Plate Loaded",
    default_reps: 12,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: ["cable_pull_through"],
    tags: ["glute_compound", "hinge"],
    day_assignment: "Legs_A",
    circuit_id: "2",
    description: "Safe hip extension without spinal loading.",
  },

  // =========================================
  // LEGS B (Focus: Posterior Chain/Stability)
  // =========================================
  {
    id: "leg_press_horizontal_01",
    name: "Horizontal Leg Press",
    target_muscle: "Quadriceps",
    machine_type: "Selectorized",
    default_reps: 15,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: ["leg_press_linear_01"],
    tags: ["quad_compound", "legs_push"],
    day_assignment: "Legs_B",
    circuit_id: "1",
    description: "Lower impact than linear press, good for volume.",
  },
  {
    id: "hamstring_curl_lying_01",
    name: "Lying Hamstring Curl",
    target_muscle: "Hamstrings",
    machine_type: "Selectorized",
    default_reps: 12,
    default_sets: 4,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: ["hamstring_curl_seated_01"],
    tags: ["hamstring_isolation"],
    day_assignment: "Legs_B",
    circuit_id: "1",
    description: "Isolates hamstrings in a lengthened position.",
  },
  {
    id: "calf_raise_standing_01",
    name: "Standing Calf Raise",
    target_muscle: "Gastrocnemius",
    machine_type: "Selectorized",
    default_reps: 15,
    default_sets: 4,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: ["calf_raise_seated_01"],
    tags: ["calf_isolation"],
    day_assignment: "Legs_B",
    circuit_id: "1",
    description: "Keep knee slightly bent to protect joint.",
  },
  {
    id: "hip_adduction_machine_01",
    name: "Hip Adduction Machine",
    target_muscle: "Adductors",
    machine_type: "Selectorized",
    default_reps: 15,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: [],
    tags: ["adduction_isolation"],
    day_assignment: "Legs_B",
    circuit_id: "2",
    description: "Inner thigh strength for knee stability.",
  },
  {
    id: "generic_hip_thrust_machine",
    name: "Machine Hip Thrust",
    target_muscle: "Glutes",
    machine_type: "Plate Loaded",
    default_reps: 12,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: [],
    tags: ["glute_compound", "hinge"],
    day_assignment: "Legs_B",
    circuit_id: "2",
    description: "Direct glute loading.",
  },
  {
    id: "glute_kickback_machine_01",
    name: "Glute Kickback Machine",
    target_muscle: "Glutes",
    machine_type: "Selectorized",
    default_reps: 15,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: [],
    tags: ["glute_isolation"],
    day_assignment: "Legs_B",
    circuit_id: "2",
    description: "Unilateral glute focus without axial loading.",
  },

  // =========================================
  // PUSH A (Chest Focus)
  // =========================================
  {
    id: "chest_press_machine_01",
    name: "Seated Chest Press",
    target_muscle: "Pectorals",
    machine_type: "Selectorized",
    default_reps: 10,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: ["incline_press_machine_01"],
    tags: ["chest_compound", "horizontal_push"],
    day_assignment: "Push_A",
    circuit_id: "1",
    description: "Heavy compound press.",
  },
  {
    id: "lateral_raise_machine_01",
    name: "Lateral Raise Machine",
    target_muscle: "Side Delt",
    machine_type: "Selectorized",
    default_reps: 15,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: ["cable_lateral_raise_01"],
    tags: ["side_delt_isolation"],
    day_assignment: "Push_A",
    circuit_id: "1",
    description: "Strict isolation for shoulder width.",
  },
  {
    id: "tricep_extension_machine_01",
    name: "Tricep Extension Machine",
    target_muscle: "Triceps",
    machine_type: "Selectorized",
    default_reps: 12,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: ["tricep_pushdown_cable_01"],
    tags: ["tricep_isolation"],
    day_assignment: "Push_A",
    circuit_id: "1",
    description: "Fixed path extension.",
  },
  {
    id: "shoulder_press_machine_01",
    name: "Overhead Press Machine",
    target_muscle: "Deltoids",
    machine_type: "Selectorized",
    default_reps: 12,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: [],
    tags: ["shoulder_compound", "vertical_push"],
    day_assignment: "Push_A",
    circuit_id: "2",
    description: "Safe overhead stability.",
  },
  {
    id: "pec_fly_machine_01",
    name: "Pec Deck / Machine Fly",
    target_muscle: "Pectorals",
    machine_type: "Selectorized",
    default_reps: 15,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: ["cable_fly_01"],
    tags: ["chest_isolation", "fly"],
    day_assignment: "Push_A",
    circuit_id: "2",
    description: "Chest isolation.",
  },
  {
    id: "dip_machine_01",
    name: "Seated Dip Machine",
    target_muscle: "Triceps/Chest",
    machine_type: "Selectorized",
    default_reps: 12,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: [],
    tags: ["tricep_compound", "vertical_push"],
    day_assignment: "Push_A",
    circuit_id: "2",
    description: "Compound movement for triceps.",
  },

  // =========================================
  // PUSH B (Shoulder/Upper Chest Focus)
  // =========================================
  {
    id: "incline_press_machine_01",
    name: "Incline Chest Press",
    target_muscle: "Upper Pecs",
    machine_type: "Plate Loaded",
    default_reps: 10,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: ["chest_press_machine_01"],
    tags: ["chest_compound", "incline_push"],
    day_assignment: "Push_B",
    circuit_id: "1",
    description: "Focus on upper shelf.",
  },
  {
    id: "lateral_raise_machine_02_copy",
    name: "Lateral Raise Machine",
    target_muscle: "Side Delt",
    machine_type: "Selectorized",
    default_reps: 15,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: ["cable_lateral_raise_01"],
    tags: ["side_delt_isolation"],
    day_assignment: "Push_B",
    circuit_id: "1",
    description: "Strict isolation for shoulder width.",
  },
  {
    id: "dip_machine_02_copy",
    name: "Seated Dip Machine",
    target_muscle: "Triceps",
    machine_type: "Selectorized",
    default_reps: 15,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: [],
    tags: ["tricep_isolation", "overhead_extension"],
    day_assignment: "Push_B",
    circuit_id: "1",
    description: "Machine dip focusing on triceps lock out.",
  },
  {
    id: "chest_press_plate_01",
    name: "Plate Loaded Chest Press",
    target_muscle: "Pectorals",
    machine_type: "Plate Loaded",
    default_reps: 10,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: ["chest_press_machine_01", "incline_press_machine_01"],
    tags: ["chest_compound", "horizontal_push"],
    day_assignment: "Push_B",
    circuit_id: "2",
    description: "Unilateral convergent pressing path.",
  },
  {
    id: "shoulder_press_plate_01",
    name: "Plate Loaded Shoulder Press",
    target_muscle: "Deltoids",
    machine_type: "Plate Loaded",
    default_reps: 10,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: ["shoulder_press_machine_01"],
    tags: ["shoulder_compound", "vertical_push"],
    day_assignment: "Push_B",
    circuit_id: "2",
    description: "Heavier overhead pressing option.",
  },
  {
    id: "generic_dumbell_shoulder_press",
    name: "Dumbbell Shoulder Press",
    target_muscle: "Deltoids",
    machine_type: "Dumbbell",
    default_reps: 10,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: [],
    tags: ["front_delt_isolation", "vertical_push"],
    day_assignment: "Push_B",
    circuit_id: "2",
    description: "Unilateral shoulder strength.",
  },

  // =========================================
  // PULL A (Lat Width Focus)
  // =========================================
  {
    id: "lat_pulldown_01",
    name: "Wide Grip Lat Pulldown",
    target_muscle: "Lats",
    machine_type: "Cable",
    default_reps: 12,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: ["pull_up_assist_01"],
    tags: ["vertical_pull", "lats"],
    day_assignment: "Pull_A",
    circuit_id: "1",
    description: "Main vertical pull.",
  },
  {
    id: "rear_delt_machine_02_copy",
    name: "Reverse Pec Deck",
    target_muscle: "Rear Delt/Rotator",
    machine_type: "Selectorized",
    default_reps: 20,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: ["face_pull_cable_01"],
    tags: ["rear_delt_isolation"],
    day_assignment: "Pull_A",
    circuit_id: "1",
    description: "Machine alternative to face pulls.",
  },
  {
    id: "bicep_curl_machine_01",
    name: "Preacher Curl Machine",
    target_muscle: "Biceps",
    machine_type: "Selectorized",
    default_reps: 12,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: ["cable_curl_01"],
    tags: ["bicep_isolation"],
    day_assignment: "Pull_A",
    circuit_id: "1",
    description: "Fixed arm support bicep curl.",
  },
  {
    id: "seated_row_machine_01",
    name: "Seated Cable Row",
    target_muscle: "Mid Back",
    machine_type: "Cable",
    default_reps: 12,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: ["t_bar_row_machine_01"],
    tags: ["horizontal_pull", "back_thickness"],
    day_assignment: "Pull_A",
    circuit_id: "2",
    description: "Horizontal rowing power.",
  },
  {
    id: "lat_pulldown_vbar_01",
    name: "V-Bar Lat Pulldown",
    target_muscle: "Lats",
    machine_type: "Cable",
    default_reps: 12,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: ["lat_pulldown_01", "close_grip_pulldown_01"],
    tags: ["vertical_pull", "lats"],
    day_assignment: "Pull_A",
    circuit_id: "2",
    description: "Neutral grip variant for lat thickness.",
  },
  {
    id: "generic_dumbell_curl",
    name: "Dumbbell Hammer Curl",
    target_muscle: "Brachialis",
    machine_type: "Dumbbell",
    default_reps: 15,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: [],
    tags: ["bicep_isolation", "forearms"],
    day_assignment: "Pull_A",
    circuit_id: "2",
    description: "Unilateral arm work.",
  },

  // =========================================
  // PULL B (Upper Back/Thickness Focus)
  // =========================================
  {
    id: "t_bar_row_machine_01",
    name: "Chest Supported Row",
    target_muscle: "Upper Back",
    machine_type: "Plate Loaded",
    default_reps: 10,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: ["seated_row_machine_01"],
    tags: ["horizontal_pull", "back_thickness"],
    day_assignment: "Pull_B",
    circuit_id: "1",
    description: "Heavy rowing with chest support.",
  },
  {
    id: "rear_delt_machine_01",
    name: "Reverse Pec Deck",
    target_muscle: "Rear Delts",
    machine_type: "Selectorized",
    default_reps: 15,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: ["face_pull_cable_01"],
    tags: ["rear_delt_isolation"],
    day_assignment: "Pull_B",
    circuit_id: "1",
    description: "Isolation for rear shoulders.",
  },
  {
    id: "bicep_curl_machine_02_copy",
    name: "Preacher Curl Machine",
    target_muscle: "Biceps",
    machine_type: "Selectorized",
    default_reps: 12,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: ["bicep_curl_machine_01"],
    tags: ["bicep_isolation"],
    day_assignment: "Pull_B",
    circuit_id: "1",
    description: "Constant tension curl.",
  },
  {
    id: "close_grip_pulldown_01",
    name: "Close Grip Pulldown",
    target_muscle: "Lats",
    machine_type: "Cable",
    default_reps: 12,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: ["lat_pulldown_01"],
    tags: ["vertical_pull", "lats"],
    day_assignment: "Pull_B",
    circuit_id: "2",
    description: "Neutral grip vertical pull.",
  },
  {
    id: "shrug_machine_01",
    name: "Machine Shrugs",
    target_muscle: "Traps",
    machine_type: "Plate/Selectorized",
    default_reps: 15,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: [],
    tags: ["traps"],
    day_assignment: "Pull_B",
    circuit_id: "2",
    description: "Upper Trap isolation.",
  },
  {
    id: "single_arm_machine_row_01",
    name: "Single Arm Machine Row",
    target_muscle: "Lats/Mid-Back",
    machine_type: "Plate Loaded",
    default_reps: 12,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Active",
    compatible_swaps: [],
    tags: ["horizontal_pull", "unilateral"],
    day_assignment: "Pull_B",
    circuit_id: "2",
    description: "Unilateral work to fix imbalances.",
  },

  // =========================================
  // BENCH (CABLES & ALTERNATIVES)
  // =========================================
  {
    id: "hack_squat_01",
    name: "Machine Hack Squat",
    target_muscle: "Quadriceps",
    machine_type: "Sled",
    default_reps: 10,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_2_CAUTION,
    status: "Bench", 
    compatible_swaps: ["leg_press_horizontal_01"],
    tags: ["quad_compound", "legs_push"],
    day_assignment: "Legs_A",
    circuit_id: "1", 
    description: "Advanced closed chain. Ensure knees don't cave in.",
  },
  {
    id: "pull_up_assist_01",
    name: "Assisted Pull Up",
    target_muscle: "Lats",
    machine_type: "Selectorized",
    default_reps: 10,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Bench",
    compatible_swaps: ["lat_pulldown_01"],
    tags: ["vertical_pull", "lats"],
    day_assignment: "Pull_A",
    circuit_id: "1", 
    description: "Bodyweight mechanics with assistance.",
  },
  {
    id: "cable_pull_through_01",
    name: "Cable Pull Through",
    target_muscle: "Glutes/Hams",
    machine_type: "Cable",
    default_reps: 15,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Bench",
    compatible_swaps: ["glute_drive_machine_01"],
    tags: ["glute_compound", "hinge"],
    day_assignment: "Legs_B",
    circuit_id: "2",
    description: "Hinge pattern practice with constant tension.",
  },
  {
    id: "tricep_pushdown_cable_01",
    name: "Tricep Pushdown (Rope)",
    target_muscle: "Triceps",
    machine_type: "Cable",
    default_reps: 15,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Bench",
    compatible_swaps: ["tricep_extension_machine_01"],
    tags: ["tricep_isolation"],
    day_assignment: "Push_A",
    circuit_id: "1",
    description: "Standard tricep builder.",
  },
  {
    id: "cable_lateral_raise_01",
    name: "Cable Lateral Raise",
    target_muscle: "Side Delt",
    machine_type: "Cable",
    default_reps: 15,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Bench",
    compatible_swaps: ["lateral_raise_machine_01"],
    tags: ["side_delt_isolation"],
    day_assignment: "Push_B",
    circuit_id: "1",
    description: "Unilateral shoulder isolation.",
  },
  {
    id: "overhead_tricep_cable_01",
    name: "Overhead Tricep Ext",
    target_muscle: "Triceps",
    machine_type: "Cable",
    default_reps: 15,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Bench",
    compatible_swaps: [],
    tags: ["tricep_isolation", "overhead_extension"],
    day_assignment: "Push_B",
    circuit_id: "1",
    description: "Long head tricep focus.",
  },
  {
    id: "cable_fly_01",
    name: "Cable Fly (High to Low)",
    target_muscle: "Lower Pecs",
    machine_type: "Cable",
    default_reps: 15,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Bench",
    compatible_swaps: ["pec_fly_machine_01"],
    tags: ["chest_isolation", "fly"],
    day_assignment: "Push_B",
    circuit_id: "2",
    description: "Constant tension chest movement.",
  },
  {
    id: "front_raise_cable_01",
    name: "Cable Front Raise",
    target_muscle: "Front Delt",
    machine_type: "Cable",
    default_reps: 15,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Bench",
    compatible_swaps: [],
    tags: ["front_delt_isolation"],
    day_assignment: "Push_B",
    circuit_id: "2",
    description: "Finisher for front delts.",
  },
  {
    id: "face_pull_cable_01",
    name: "Cable Face Pull",
    target_muscle: "Rear Delt/Rotator",
    machine_type: "Cable",
    default_reps: 20,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Bench",
    compatible_swaps: ["rear_delt_machine_01"],
    tags: ["rear_delt_isolation"],
    day_assignment: "Pull_A",
    circuit_id: "1",
    description: "Postural health and rear delts.",
  },
  {
    id: "straight_arm_pulldown_01",
    name: "Straight Arm Pulldown",
    target_muscle: "Lats",
    machine_type: "Cable",
    default_reps: 15,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Bench",
    compatible_swaps: [],
    tags: ["lat_isolation"],
    day_assignment: "Pull_A",
    circuit_id: "2",
    description: "Lat isolation without biceps.",
  },
  {
    id: "cable_hammer_curl_01",
    name: "Rope Hammer Curl",
    target_muscle: "Brachialis",
    machine_type: "Cable",
    default_reps: 15,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Bench",
    compatible_swaps: [],
    tags: ["bicep_isolation", "forearms"],
    day_assignment: "Pull_A",
    circuit_id: "2",
    description: "Forearm and outer bicep width.",
  },
  {
    id: "cable_curl_01",
    name: "Standing Cable Curl",
    target_muscle: "Biceps",
    machine_type: "Cable",
    default_reps: 12,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Bench",
    compatible_swaps: ["bicep_curl_machine_01"],
    tags: ["bicep_isolation"],
    day_assignment: "Pull_B",
    circuit_id: "1",
    description: "Constant tension curl.",
  },
  {
    id: "single_arm_cable_row_01",
    name: "Single Arm Cable Row",
    target_muscle: "Lats/Mid-Back",
    machine_type: "Cable",
    default_reps: 12,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Bench",
    compatible_swaps: [],
    tags: ["horizontal_pull", "unilateral"],
    day_assignment: "Pull_B",
    circuit_id: "2",
    description: "Unilateral work to fix imbalances.",
  },
  {
    id: "seated_leg_curl_02",
    name: "Unilateral Seated Leg Curl",
    target_muscle: "Hamstrings",
    machine_type: "Selectorized",
    default_reps: 12,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Bench",
    compatible_swaps: ["hamstring_curl_seated_01"],
    tags: ["hamstring_isolation"],
    day_assignment: "Legs_A",
    circuit_id: "1",
    description: "Focus on one leg at a time.",
  },
  {
    id: "donkey_calf_raise_01",
    name: "Donkey Calf Raise Machine",
    target_muscle: "Gastrocnemius",
    machine_type: "Selectorized",
    default_reps: 15,
    default_sets: 4,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Bench",
    compatible_swaps: ["calf_raise_standing_01"],
    tags: ["calf_isolation"],
    day_assignment: "Legs_B",
    circuit_id: "1",
    description: "Strict calf isolation with spinal support.",
  },
  {
    id: "generic_dumbell_press_flat",
    name: "Dumbbell Chest Press",
    target_muscle: "Pectorals",
    machine_type: "Dumbbell",
    default_reps: 10,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Bench",
    compatible_swaps: [],
    tags: ["chest_compound", "horizontal_push"],
    day_assignment: "Push_A",
    circuit_id: "1",
    description: "Stabilizer heavy chest movement.",
  },
  {
    id: "generic_cable_row_unilateral",
    name: "Unilateral Cable Row",
    target_muscle: "Lats",
    machine_type: "Cable",
    default_reps: 12,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Bench",
    compatible_swaps: [],
    tags: ["horizontal_pull", "back_thickness"],
    day_assignment: "Pull_A",
    circuit_id: "2",
    description: "Great for fixing imbalances.",
  },
  {
    id: "generic_goblet_squat",
    name: "Goblet Squat (DB)",
    target_muscle: "Quadriceps/Core",
    machine_type: "Dumbbell",
    default_reps: 12,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Bench",
    compatible_swaps: [],
    tags: ["quad_compound", "legs_push"],
    day_assignment: "Legs_A",
    circuit_id: "1",
    description: "Anterior loaded squat, safe for back.",
  },
  {
    id: "generic_inner_thigh_cable",
    name: "Cable Adduction",
    target_muscle: "Adductors",
    machine_type: "Cable",
    default_reps: 15,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Bench",
    compatible_swaps: [],
    tags: ["adduction_isolation"],
    day_assignment: "Legs_B",
    circuit_id: "2",
    description: "Standing cable inner thigh work.",
  },
  {
    id: "generic_outer_thigh_cable",
    name: "Cable Abduction",
    target_muscle: "Abductors",
    machine_type: "Cable",
    default_reps: 15,
    default_sets: 3,
    acl_safety_tier: ACLSafetyTier.TIER_1_SAFE,
    status: "Bench",
    compatible_swaps: [],
    tags: ["abduction_isolation"],
    day_assignment: "Legs_A",
    circuit_id: "2",
    description: "Standing cable outer thigh work.",
  }
];

export const SCHEDULE_DAYS = [
  { id: 1, label: "Mon", workoutName: "Push: Chest & Triceps", type: "Push_A" },
  { id: 2, label: "Tue", workoutName: "Pull: Vertical & Lats", type: "Pull_A" },
  { id: 3, label: "Wed", workoutName: "Legs: Quads & Stability", type: "Legs_A" },
  { id: 4, label: "Thu", workoutName: "Push: Shoulders & Incline", type: "Push_B" },
  { id: 5, label: "Fri", workoutName: "Pull: Horizontal & Thickness", type: "Pull_B" },
  { id: 6, label: "Sat", workoutName: "Legs: Hamstrings & Glutes", type: "Legs_B" },
];